# Generated by Django 6.0.2 on 2026-09-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.URLField()),
                ('altitude_range', models.CharField(blank=True, max_length=100)),
                ('best_time', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='General', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('location_visited', models.CharField(default='Kashmir', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=150)),
                ('capacity_passengers', models.CharField(max_length=100)),
                ('terrain_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('badge', models.CharField(default='4x4 Beast', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(default='Main Character Energy in the Himalayas ⚡', max_length=255)),
                ('vibe_tag', models.CharField(default='#SnowVibes', max_length=100)),
                ('duration_days', models.IntegerField(default=5)),
                ('duration_nights', models.IntegerField(default=4)),
                ('starting_price', models.IntegerField(default=15999)),
                ('difficulty', models.CharField(default='Moderate', max_length=50)),
                ('cover_image', models.URLField()),
                ('gallery_urls', models.JSONField(blank=True, default=list)),
                ('overview', models.TextField()),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('travel_dates', models.CharField(blank=True, max_length=100)),
                ('travelers_count', models.IntegerField(default=2)),
                ('vehicle_preference', models.CharField(blank=True, max_length=100)),
                ('custom_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='Guide', max_length=100)),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('author', models.CharField(default='Flavour Squad', max_length=100)),
                ('cover_image', models.URLField()),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('vibe_tag', models.CharField(default='#TravelHacks', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=150)),
                ('altitude', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('insta_spot', models.CharField(blank=True, max_length=250)),
                ('vibe_highlight', models.CharField(blank=True, max_length=250)),
                ('image_url', models.URLField(blank=True)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
