# Generated by Django 6.0.2 on 2026-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_bookingsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cover_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tourcheckpoint',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='checkpoints/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tourcheckpoint',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
